### ISSUE TITLE
Octave process running endlessly

### ISSUE THREAD

**Issue by DL8LAQ** [llinkz/directTDoA#10]
Hi,

we are trying the new version 7.10.

After the recording is finished, the explorer window opens and shows the saved files. Then I start the tdoa process, a terminal window opens for a few seconds and then there is the pdf file with the spectra of the received data. Now the Octave process runs endlessly... The process can be canceled, but no changes appear in the explorer window.

We are at least three users who can't get the Octave process running.

 73, Norbert

**Comment by llinkz** [comment]
Hi

I need more informations
  Which OS? if Linux which Octave version ?  (I hope it's not MacOS because I don't know it very well)
  Contains of the TDoA_xxxxxxxx_log.txt (even if Octave running endlessly)
  I think you use the standard TDoA mode, right ?
  How do you switch to v7.10 version ?  running from scratch with _git clone --recursive_ or just retrieving the modified .py files
  Did you run the setup.py if you're on linux ? and did you get more than warnings in the log ?
  If you run octave-gui and type _pkg list_ do you see control & signal modules loaded ?

**Bug discovered:**
I have noticed I forgot to change __spec.pdf_ in the code because plot_iq.py is now naming the spectrum files as __spectrogram.pdf_
I'll correct it in the next commit
At the moment it's just bypassing the addition of the spectrum as 3rd page of the final .pdf because of the file name wrong syntax...


I have tested both Linux 7.10 & Windows 7.10 version and Octave works fine
octave --silent --eval "pkg list"
control  |   3.4.0 | .../.local/share/octave/api-v57/packages/control-3.4.0
signal  |   1.4.3 | .../.local/share/octave/api-v57/packages/signal-1.4.3
octave --silent --eval "version" 
ans = 7.3.0

Regards
(I'm out for a week, I'll check your answers and correct on next week-end)

**Comment by DL8LAQ** [comment]
Hi!

We are running the Windows version. I will try the Linux version during the next days.

I will answer in more detail tomorrow!

 73, Norbert

**Comment by DL8LAQ** [comment]
Hi!

Here is the TDoA log file 
[TDoA_14414000_log.txt](https://github.com/llinkz/directTDoA/files/12320387/TDoA_14414000_log.txt)

Using windows admin console I cannot find a path C:\Users\shack\... The user installing and running s/w on this pc is "Norbert".
Starting the directTDoA.bat from within the admin console doesn't change anything.

 73, Norbert

**Comment by llinkz** [comment]
Hi Norbert

I'm sorry but I was not the Windows package manager and it looks like I've made something wrong during the last release

I think the problem are the path declared in the file **\directTDoA\octave\share\octave\octave_package**s

All lines 
```
C:\Users\shack\Desktop\directTDoA\octave\share\octave\packages\control-3.2.0
C:\Users\shack\Desktop\directTDoA\octave\lib\octave\packages\control-3.2.0
C:\Users\shack\Desktop\directTDoA\octave\share\octave\packages\signal-1.4.1
C:\Users\shack\Desktop\directTDoA\octave\lib\octave\packages\signal-1.4.1
```  
should be modified like this:
```
__OH__/share/octave/packages/control-3.2.0
__OH__/lib/octave/packages/control-3.2.0
__OH__/share/octave/packages/signal-1.4.1
__OH__/lib/octave/packages/signal-1.4.1
``` 

Tell me if that fixed the problem

73

**Comment by DL8LAQ** [comment]
Path problem is fixed! The paths are changed to the correct location of DirectTDoA after the first run.
I also created a mapbox account and get the PDF files. Thank you!

**Comment by llinkz** [comment]
Thanks Norbert
Windows package modified.

73
